spring.application.name=QLDatVe

# ==================================
# Database Configuration (PostgreSQL)
# ==================================
spring.datasource.url=jdbc:postgresql://localhost:5432/QLDatVeXe
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# JPA / Hibernate Configuration
# ================================
# Tự động cập nhật CSDL. Dùng 'validate' hoặc 'none' khi deploy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================================
# Logging Configuration
# ================================
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ================================
# Server Configuration
# ================================
server.port=8081

# ================================
# Email Configuration (Gmail)
# ================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khanh0929034803@gmail.com
spring.mail.password=npnx pohf ejgz ymbv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================================
# JWT Configuration
# ================================
jwt.secret=KiOh7+vsq0sFc8wEhbgQeesll07bT0Vftn6LwzVPcAY=

# ================================
# MoMo Configuration (TEST Environment)
# ================================
momo.partnerCode=MOMO
momo.accessKey=F8BBA842ECF85
momo.secretKey=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.api.endpoint=https://test-payment.momo.vn/v2/gateway/api/create

# Frontend URL MoMo chuyển hướng về
momo.redirectUrl=http://localhost:3000/payment/momo/return

# Backend Webhook URL (IPN) - PHẢI LÀ URL PUBLIC
# Thay thế URL_NGROK... bằng URL ngrok của bạn
momo.ipnUrl=https://pleasureful-overinterestedly-sanjuanita.ngrok-free.dev/api/payment/momo-ipn
# --------------------------------------------------------------------